---
 - hosts: all
   remote_user: ubuntu
   become_method: sudo
   become: true

   tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: Starting apache services
      service:
              name: "apache2"
              state: started
              enabled: yes